### ISSUE TITLE
Json parse error on consul 1.10.4

### ISSUE THREAD

**Issue by keyliaran** [jmgilman/consulrs#13]
Im trying to list all registered services on consul 1.10.4. And its seems that serde_json can't parse response from consul. 
`ResponseParseError { source: invalid type: map, expected a string at line 1 column 135, content: Some(\"{\\\"test_service\\\":{\\\"ID\\\":\\\"test_service\\\",\\\"Service\\\":\\\"test_service\\\",\\\"Tags\\\":[],\\\"Meta\\\":{},\\\"Port\\\":1234,\\\"Address\\\":\\\"172.22.0.5\\\",\\\"TaggedAddresses\\\":{\\\"lan_ipv4\\\":{\\\"Address\\\":\\\"172.22.0.5\\\",\\\"Port\\\":1234},\\\"wan_ipv4\\\":{\\\"Address\\\":\\\"172.22.0.5\\\",\\\"Port\\\":1234}},\\\"Weights\\\":{\\\"Passing\\\":1,\\\"Warning\\\":1},\\\"EnableTagOverride\\\":false,\\\"Datacenter\\\":\\\"dc1\\\"}}\") } }"`

**Comment by jmgilman** [comment]
Would you be able to replicate the request and post the actual JSON content for review?

**Comment by keyliaran** [comment]
request: curl http://127.0.0.1:8500/v1/agent/services
Json:
```json{
   "my_service":{
      "ID":"my_service",
      "Service":"my_service",
      "Tags":[
         
      ],
      "Meta":{
         
      },
      "Port":1234,
      "Address":"172.22.0.5",
      "TaggedAddresses":{
         "lan_ipv4":{
            "Address":"172.22.0.5",
            "Port":1234
         },
         "wan_ipv4":{
            "Address":"172.22.0.5",
            "Port":1234
         }
      },
      "Weights":{
         "Passing":1,
         "Warning":1
      },
      "EnableTagOverride":false,
      "Datacenter":"dc1"
   }
}

**Comment by jmgilman** [comment]
Can you verify that #14 fixes this?

**Comment by keyliaran** [comment]
Works for me

**Comment by CDFN** [comment]
It would be nice if this change was pushed to crates.io. For anyone who wants it use before it's pushed, you can specify your dependency like so: `consulrs = { git = "https://github.com/jmgilman/consulrs" }`
